libjwt-1.7.0: JWT Output Functions
JWT Output Functions
Functions that enable seeing the plain text or fully encoded version of a JWT object.
Functions
int jwt_dump_fp (jwt_t *jwt, FILE *fp, int pretty)
Output plain text representation to a FILE pointer.
char * jwt_dump_str (jwt_t *jwt, int pretty)
Return plain text representation as a string.
int jwt_encode_fp (jwt_t *jwt, FILE *fp)
Fully encode a JWT object and write it to FILE.
char * jwt_encode_str (jwt_t *jwt)
Fully encode a JWT object and return as a string.
Detailed Description
Functions that enable seeing the plain text or fully encoded version of a JWT object.
Function Documentation
int jwt_dump_fp (jwt_t * jwt, FILE * fp, int pretty)
Output plain text representation to a FILE pointer.
This function will write a plain text representation of this JWT object without Base64 encoding. This only writes the header and body, and does not compute the signature or encryption (if such an algorithm were being used).
Parameters
jwt Pointer to a JWT object.
fp Valid FILE pointer to write data to.
pretty Enables better visual formatting of output. Generally only used for debugging.
Returns
Returns 0 on success, valid errno otherwise.
Referenced by jwt_del_grant().
char* jwt_dump_str (jwt_t * jwt, int pretty)
Return plain text representation as a string.
Similar to jwt_dump_fp() except that a string is returned. The string must be freed by the caller.
Parameters
jwt Pointer to a JWT object.
pretty Enables better visual formatting of output. Generally only used for debugging.
Returns
A nul terminated string on success, NULL on error with errno set appropriately.
Referenced by jwt_del_grant().
int jwt_encode_fp (jwt_t * jwt, FILE * fp)
Fully encode a JWT object and write it to FILE.
This will create and write the complete JWT object to FILE. All parts will be Base64 encoded and signatures or encryption will be applied if the algorithm specified requires it.
Parameters
jwt Pointer to a JWT object.
fp Valid FILE pointer to write data to.
Returns
Returns 0 on success, valid errno otherwise.
Referenced by jwt_del_grant().
char* jwt_encode_str (jwt_t * jwt)
Fully encode a JWT object and return as a string.
Similar to jwt_encode_fp() except that a string is returned. The string must be freed by the caller.
Parameters
jwt Pointer to a JWT object.
Returns
A nul terminated string on success, NULL on error with errno set appropriately.
Referenced by jwt_del_grant().