name: LibJWT Build, Unit Tests, and Coverage

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "doxygen/**"
      - ".github/**"
      - "images/**"
      - ".gitignore"
      - "*.md"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "doxygen/**"
      - ".github/**"
      - "images/**"
      - ".gitignore"
      - "*.md"

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ConorMacBride/install-package@v1
      with:
        brew: gnutls openssl@3 jansson pkgconf cmake check curl bats-core jq

    - name: Build and Test
      uses: threeal/cmake-action@v2.1.0
      with:
        options:
          WITH_LIBCURL=YES
        build-args: |
          --
          all
          check

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ConorMacBride/install-package@v1
      with:
        apt: gnutls-dev libssl-dev libjansson-dev pkg-config check lcov valgrind libcurl4-openssl-dev bats jq

    - name: Build, Test, and Coverage
      uses: threeal/cmake-action@v2.1.0
      with:
        options: |
          ENABLE_COVERAGE=YES
          WITH_LIBCURL=YES
        build-args: |
          --
          all
          check-code-coverage

    - uses: codecov/codecov-action@v5.1.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{github.workspace}}/build/check-code-coverage.info
        disable_search: true
        verbose: true

    - name: Memcheck
      working-directory: ${{github.workspace}}/build
      run: ctest -T memcheck
